package src;
import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.JLabel;
import java.awt.Font;
import java.awt.Component;
import javax.swing.ImageIcon;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

public class JFrame_StudentDashboard extends JFrame {

	//private JPanel contentPane;	
	private String username;
	
	public JFrame_StudentDashboard(String username) {
        this.username=username;
    	initComponents();
    }

    public String getUsername() {
		return username;
	}
	/*public void run() {
		try {
				JFrame_StudentDashboard frame = new JFrame_StudentDashboard(username);
					//frame.setVisible(true);
			}
		catch (Exception e) {
				e.printStackTrace();
			}
		}
*/
    
    
		/**
		     * This method is called from within the constructor to initialize the form.
		     * WARNING: Do NOT modify this code. The content of this method is always
		     * regenerated by the Form Editor.
		     */
		    @SuppressWarnings("unchecked")
		    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
public void initComponents() {

		        jPanel1 = new javax.swing.JPanel();
		        jPanel2 = new javax.swing.JPanel();
		        jLabel13 = new javax.swing.JLabel();
		        exit = new javax.swing.JLabel();
		        jLabel15 = new javax.swing.JLabel();
		        jLabel15.setText(username);
		        jTextField1 = new javax.swing.JTextField();
		        jSeparator1 = new javax.swing.JSeparator();
		        jLabel14 = new javax.swing.JLabel();
		        jLabel16 = new javax.swing.JLabel();
		        notifications_jPanel = new javax.swing.JPanel();
		        notifications_jLabel_img = new javax.swing.JLabel();
		        notifications_jLabel_img.setIcon(new ImageIcon("Images\\icons8-notification-96.png"));
		        jLabel1 = new javax.swing.JLabel();
		        home_jPanel = new javax.swing.JPanel();
		        home_jPanel.setFont(new Font("Comic Sans MS", Font.BOLD, 16));
		        home_jPanel.setAlignmentY(Component.BOTTOM_ALIGNMENT);
		        home_jPanel.setAlignmentX(Component.RIGHT_ALIGNMENT);
		        profile_jlabel_img = new javax.swing.JLabel();
		        profile_jlabel_img.addMouseListener(new MouseAdapter() {
		        	@Override
		        	public void mouseEntered(MouseEvent arg0) {
		        	}
		        });
		        profile_jlabel_img.setIcon(new ImageIcon("Images\\icons8-profile-96.png"));
		        jLabel4 = new javax.swing.JLabel();
		        course_jPanel5 = new javax.swing.JPanel();
		        courses_jLabel_img = new javax.swing.JLabel();
		        courses_jLabel_img.setIcon(new ImageIcon("Images\\icons8-books-96.png"));
		        jLabel6 = new javax.swing.JLabel();
		        grades_jPanel = new javax.swing.JPanel();
		        grades_jLabel_img = new javax.swing.JLabel();
		        grades_jLabel_img.setIcon(new ImageIcon("Images\\icons8-grades-96.png"));
		        jLabel8 = new javax.swing.JLabel();
		        settings_jPanel = new javax.swing.JPanel();
		        settings_jPanel.setForeground(new Color(0, 0, 0));
		        settings_jLabel_img = new javax.swing.JLabel();
		        settings_jLabel_img.setIcon(new ImageIcon("Images\\icons8-briefcase-settings-96.png"));
		        jLabel10 = new javax.swing.JLabel();
		        Finacial_accnt_jPanel = new javax.swing.JPanel();
		        financial_accnt_jLabel_img = new javax.swing.JLabel();
		        financial_accnt_jLabel_img.setIcon(new ImageIcon("Images\\icons8-financial-tasks-96.png"));
		        jLabel12 = new javax.swing.JLabel();

		        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		        setLocationByPlatform(true);
		        setUndecorated(true);
		        setPreferredSize(new java.awt.Dimension(860, 650));

		        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
		        jPanel1.setMinimumSize(new java.awt.Dimension(860, 600));
		        jPanel1.setPreferredSize(new java.awt.Dimension(854, 600));
		        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		        jPanel2.setBackground(new Color(51, 102, 204));
		        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
		            public void mouseDragged(java.awt.event.MouseEvent evt) {
		                jPanel2MouseDragged(evt);
		            }
		        });
		        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
		            public void mousePressed(java.awt.event.MouseEvent evt) {
		                jPanel2MousePressed(evt);
		            }
		        });
		        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
		        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
		        jLabel13.setText("Dashboard");
		        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

		        exit.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
		        exit.setForeground(new java.awt.Color(255, 255, 255));
		        exit.setText("X");
		        exit.addMouseListener(new java.awt.event.MouseAdapter() {
		            public void mousePressed(java.awt.event.MouseEvent evt) {
		                exitMousePressed(evt);
		            }
		        });
		        jPanel2.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(838, 0, 22, -1));

		        jLabel15.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
		        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
		        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

		        jTextField1.setBackground(new java.awt.Color(45, 118, 232));
		        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
		        jTextField1.setBorder(null);
		        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 334, 25));
		        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 348, -1));

		        jLabel14.setIcon(new javax.swing.ImageIcon("\\Images\\navigation.png")); // NOI18N
		        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 90, 100));

		        jLabel16.setIcon(new javax.swing.ImageIcon("\\Images\\search_20px_1.png")); // NOI18N
		        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, -1));

		        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 240));

		        notifications_jPanel.setBackground(new Color(51, 102, 204));
		        notifications_jPanel.addMouseListener(new java.awt.event.MouseAdapter() {
		            public void mouseEntered(java.awt.event.MouseEvent evt) {
		                jPanel3MouseEntered(evt);
		            }
		            public void mouseExited(java.awt.event.MouseEvent evt) {
		                jPanel3MouseExited(evt);
		            }
		        });

		        notifications_jLabel_img.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		        notifications_jLabel_img.setForeground(new java.awt.Color(45, 118, 232));
		        notifications_jLabel_img.setText("Update");

		        jLabel1.setIcon(new javax.swing.ImageIcon("Images\\download_52px.png")); // NOI18N
		        
		        notifications_jlabel = new JLabel("Notifications");
		        notifications_jlabel.setFont(new Font("Comic Sans MS", Font.BOLD, 16));

		        javax.swing.GroupLayout gl_notifications_jPanel = new javax.swing.GroupLayout(notifications_jPanel);
		        gl_notifications_jPanel.setHorizontalGroup(
		        	gl_notifications_jPanel.createParallelGroup(Alignment.LEADING)
		        		.addGroup(gl_notifications_jPanel.createSequentialGroup()
		        			.addGroup(gl_notifications_jPanel.createParallelGroup(Alignment.LEADING)
		        				.addGroup(gl_notifications_jPanel.createSequentialGroup()
		        					.addGap(46)
		        					.addComponent(jLabel1))
		        				.addGroup(gl_notifications_jPanel.createSequentialGroup()
		        					.addGap(19)
		        					.addGroup(gl_notifications_jPanel.createParallelGroup(Alignment.TRAILING)
		        						.addComponent(notifications_jLabel_img, GroupLayout.PREFERRED_SIZE, 102, GroupLayout.PREFERRED_SIZE)
		        						.addComponent(notifications_jlabel))))
		        			.addContainerGap(19, Short.MAX_VALUE))
		        );
		        gl_notifications_jPanel.setVerticalGroup(
		        	gl_notifications_jPanel.createParallelGroup(Alignment.LEADING)
		        		.addGroup(gl_notifications_jPanel.createSequentialGroup()
		        			.addComponent(notifications_jlabel)
		        			.addGap(6)
		        			.addComponent(jLabel1)
		        			.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		        			.addComponent(notifications_jLabel_img, GroupLayout.PREFERRED_SIZE, 83, GroupLayout.PREFERRED_SIZE)
		        			.addGap(8))
		        );
		        notifications_jPanel.setLayout(gl_notifications_jPanel);

		        jPanel1.add(notifications_jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, 140, 120));

		        home_jPanel.setBackground(new Color(51, 102, 204));
		        home_jPanel.addMouseListener(new java.awt.event.MouseAdapter() {
		            public void mouseEntered(java.awt.event.MouseEvent evt) {
		                jPanel4MouseEntered(evt);
		            }
		            public void mouseExited(java.awt.event.MouseEvent evt) {
		                jPanel4MouseExited(evt);
		            }
		            //public void mousePressed(java.awt.event.MouseEvent evt) {
		              //  jPanel4MousePressed(evt);
		            //}
		            public void mouseClicked(java.awt.event.MouseEvent evt) {
		                jPanel4MouseClicked(evt);
		            }
		        });

		        profile_jlabel_img.setFont(new Font("Comic Sans MS", Font.BOLD, 16)); // NOI18N
		        profile_jlabel_img.setForeground(new java.awt.Color(45, 118, 232));

		        jLabel4.setIcon(new javax.swing.ImageIcon("Images\\home_48px.png")); // NOI18N
		        
		        JLabel profile_jlabel = new JLabel("Profile");
		        profile_jlabel.setForeground(new Color(0, 0, 0));
		        profile_jlabel.setFont(new Font("Comic Sans MS", Font.BOLD, 16));

		        javax.swing.GroupLayout gl_home_jPanel = new javax.swing.GroupLayout(home_jPanel);
		        gl_home_jPanel.setHorizontalGroup(
		        	gl_home_jPanel.createParallelGroup(Alignment.TRAILING)
		        		.addGroup(gl_home_jPanel.createSequentialGroup()
		        			.addGap(140)
		        			.addComponent(jLabel4)
		        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		        		.addGroup(Alignment.LEADING, gl_home_jPanel.createSequentialGroup()
		        			.addGap(32)
		        			.addGroup(gl_home_jPanel.createParallelGroup(Alignment.LEADING)
		        				.addComponent(profile_jlabel_img)
		        				.addComponent(profile_jlabel))
		        			.addContainerGap(15, Short.MAX_VALUE))
		        );
		        gl_home_jPanel.setVerticalGroup(
		        	gl_home_jPanel.createParallelGroup(Alignment.LEADING)
		        		.addGroup(gl_home_jPanel.createSequentialGroup()
		        			.addComponent(profile_jlabel)
		        			.addGap(6)
		        			.addGroup(gl_home_jPanel.createParallelGroup(Alignment.LEADING)
		        				.addComponent(jLabel4)
		        				.addComponent(profile_jlabel_img, GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE))
		        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		        );
		        home_jPanel.setLayout(gl_home_jPanel);

		        jPanel1.add(home_jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 140, 120));

		        course_jPanel5.setBackground(new Color(51, 102, 204));
		        course_jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
		            public void mouseEntered(java.awt.event.MouseEvent evt) {
		                jPanel5MouseEntered(evt);
		            }
		            public void mouseExited(java.awt.event.MouseEvent evt) {
		                jPanel5MouseExited(evt);
		            }
		            public void mousePressed(java.awt.event.MouseEvent evt) {
		                jPanel5MousePressed(evt);
		            }
		        });

		        courses_jLabel_img.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		        courses_jLabel_img.setForeground(new java.awt.Color(45, 118, 232));

		        jLabel6.setIcon(new javax.swing.ImageIcon("Images\\group_52px.png")); // NOI18N
		        
		        courses_jlabel = new JLabel("Courses");
		        courses_jlabel.setFont(new Font("Comic Sans MS", Font.BOLD, 16));

		        javax.swing.GroupLayout gl_course_jPanel5 = new javax.swing.GroupLayout(course_jPanel5);
		        gl_course_jPanel5.setHorizontalGroup(
		        	gl_course_jPanel5.createParallelGroup(Alignment.LEADING)
		        		.addGroup(gl_course_jPanel5.createSequentialGroup()
		        			.addGroup(gl_course_jPanel5.createParallelGroup(Alignment.LEADING)
		        				.addGroup(gl_course_jPanel5.createSequentialGroup()
		        					.addGap(131)
		        					.addComponent(jLabel6))
		        				.addGroup(gl_course_jPanel5.createSequentialGroup()
		        					.addGap(42)
		        					.addComponent(courses_jlabel))
		        				.addGroup(gl_course_jPanel5.createSequentialGroup()
		        					.addGap(21)
		        					.addComponent(courses_jLabel_img)))
		        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		        );
		        gl_course_jPanel5.setVerticalGroup(
		        	gl_course_jPanel5.createParallelGroup(Alignment.LEADING)
		        		.addGroup(gl_course_jPanel5.createSequentialGroup()
		        			.addComponent(courses_jlabel)
		        			.addGap(6)
		        			.addGroup(gl_course_jPanel5.createParallelGroup(Alignment.LEADING)
		        				.addComponent(jLabel6)
		        				.addComponent(courses_jLabel_img, GroupLayout.PREFERRED_SIZE, 81, Short.MAX_VALUE))
		        			.addContainerGap())
		        );
		        course_jPanel5.setLayout(gl_course_jPanel5);

		        jPanel1.add(course_jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 140, 120));

		        grades_jPanel.setBackground(new Color(51, 102, 204));
		        grades_jPanel.addMouseListener(new java.awt.event.MouseAdapter() {
		            public void mouseEntered(java.awt.event.MouseEvent evt) {
		                jPanel6MouseEntered(evt);
		            }
		            public void mouseExited(java.awt.event.MouseEvent evt) {
		                jPanel6MouseExited(evt);
		            }
		        });

		        grades_jLabel_img.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		        grades_jLabel_img.setForeground(new java.awt.Color(45, 118, 232));

		        jLabel8.setIcon(new javax.swing.ImageIcon("Images\\classroom_48px.png")); // NOI18N
		        
		        grades_jlabel = new JLabel("Grades");
		        grades_jlabel.setFont(new Font("Comic Sans MS", Font.BOLD, 16));

		        javax.swing.GroupLayout gl_grades_jPanel = new javax.swing.GroupLayout(grades_jPanel);
		        gl_grades_jPanel.setHorizontalGroup(
		        	gl_grades_jPanel.createParallelGroup(Alignment.TRAILING)
		        		.addGroup(gl_grades_jPanel.createSequentialGroup()
		        			.addGroup(gl_grades_jPanel.createParallelGroup(Alignment.LEADING)
		        				.addGroup(gl_grades_jPanel.createSequentialGroup()
		        					.addGap(46)
		        					.addComponent(jLabel8))
		        				.addGroup(gl_grades_jPanel.createSequentialGroup()
		        					.addGap(38)
		        					.addComponent(grades_jlabel))
		        				.addGroup(gl_grades_jPanel.createSequentialGroup()
		        					.addGap(23)
		        					.addComponent(grades_jLabel_img)))
		        			.addContainerGap(21, Short.MAX_VALUE))
		        );
		        gl_grades_jPanel.setVerticalGroup(
		        	gl_grades_jPanel.createParallelGroup(Alignment.LEADING)
		        		.addGroup(gl_grades_jPanel.createSequentialGroup()
		        			.addComponent(grades_jlabel)
		        			.addGap(6)
		        			.addComponent(jLabel8)
		        			.addPreferredGap(ComponentPlacement.RELATED)
		        			.addComponent(grades_jLabel_img, GroupLayout.PREFERRED_SIZE, 84, Short.MAX_VALUE))
		        );
		        grades_jPanel.setLayout(gl_grades_jPanel);

		        jPanel1.add(grades_jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 140, 120));

		        settings_jPanel.setBackground(new Color(51, 102, 204));
		        settings_jPanel.addMouseListener(new java.awt.event.MouseAdapter() {
		            public void mouseEntered(java.awt.event.MouseEvent evt) {
		                jPanel7MouseEntered(evt);
		            }
		            public void mouseExited(java.awt.event.MouseEvent evt) {
		                jPanel7MouseExited(evt);
		            }
		        	@Override
		        	public void mouseClicked(java.awt.event.MouseEvent evt) {
		        		jPanel7MouseClicked(evt);
		        	}
		        });

		        settings_jLabel_img.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		        settings_jLabel_img.setForeground(new java.awt.Color(45, 118, 232));

		        jLabel10.setIcon(new javax.swing.ImageIcon("Images\\settings_48px.png")); // NOI18N
		        
		        settings_jlabel = new JLabel("Settings");
		        settings_jlabel.setFont(new Font("Comic Sans MS", Font.BOLD, 16));

		        javax.swing.GroupLayout gl_settings_jPanel = new javax.swing.GroupLayout(settings_jPanel);
		        gl_settings_jPanel.setHorizontalGroup(
		        	gl_settings_jPanel.createParallelGroup(Alignment.TRAILING)
		        		.addGroup(gl_settings_jPanel.createSequentialGroup()
		        			.addContainerGap(17, Short.MAX_VALUE)
		        			.addGroup(gl_settings_jPanel.createParallelGroup(Alignment.LEADING)
		        				.addGroup(gl_settings_jPanel.createSequentialGroup()
		        					.addComponent(jLabel10)
		        					.addPreferredGap(ComponentPlacement.RELATED)
		        					.addComponent(settings_jLabel_img)
		        					.addGap(20))
		        				.addGroup(Alignment.TRAILING, gl_settings_jPanel.createSequentialGroup()
		        					.addComponent(settings_jlabel)
		        					.addGap(41))))
		        );
		        gl_settings_jPanel.setVerticalGroup(
		        	gl_settings_jPanel.createParallelGroup(Alignment.LEADING)
		        		.addGroup(gl_settings_jPanel.createSequentialGroup()
		        			.addGroup(gl_settings_jPanel.createParallelGroup(Alignment.LEADING)
		        				.addGroup(gl_settings_jPanel.createSequentialGroup()
		        					.addGap(85)
		        					.addComponent(jLabel10))
		        				.addGroup(Alignment.TRAILING, gl_settings_jPanel.createSequentialGroup()
		        					.addComponent(settings_jlabel)
		        					.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		        					.addComponent(settings_jLabel_img, GroupLayout.PREFERRED_SIZE, 84, GroupLayout.PREFERRED_SIZE)))
		        			.addContainerGap())
		        );
		        settings_jPanel.setLayout(gl_settings_jPanel);

		        jPanel1.add(settings_jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 140, 120));

		        Finacial_accnt_jPanel.setBackground(new Color(51, 102, 204));
		        Finacial_accnt_jPanel.addMouseListener(new java.awt.event.MouseAdapter() {
		            public void mouseEntered(java.awt.event.MouseEvent evt) {
		                jPanel8MouseEntered(evt);
		            }
		            public void mouseExited(java.awt.event.MouseEvent evt) {
		                jPanel8MouseExited(evt);
		            }
		        });

		        financial_accnt_jLabel_img.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		        financial_accnt_jLabel_img.setForeground(new java.awt.Color(45, 118, 232));
		        financial_accnt_jLabel_img.setText("Classes");

		        jLabel12.setIcon(new javax.swing.ImageIcon("Images\\list_64px.png")); // NOI18N
		        
		        financial_account_jlabel = new JLabel("Financial Account");
		        financial_account_jlabel.setFont(new Font("Comic Sans MS", Font.BOLD, 15));

		        javax.swing.GroupLayout gl_Finacial_accnt_jPanel = new javax.swing.GroupLayout(Finacial_accnt_jPanel);
		        gl_Finacial_accnt_jPanel.setHorizontalGroup(
		        	gl_Finacial_accnt_jPanel.createParallelGroup(Alignment.TRAILING)
		        		.addGroup(gl_Finacial_accnt_jPanel.createSequentialGroup()
		        			.addGap(38)
		        			.addComponent(jLabel12)
		        			.addContainerGap(102, Short.MAX_VALUE))
		        		.addGroup(gl_Finacial_accnt_jPanel.createSequentialGroup()
		        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		        			.addGroup(gl_Finacial_accnt_jPanel.createParallelGroup(Alignment.LEADING)
		        				.addGroup(gl_Finacial_accnt_jPanel.createSequentialGroup()
		        					.addGap(10)
		        					.addComponent(financial_accnt_jLabel_img, GroupLayout.PREFERRED_SIZE, 94, GroupLayout.PREFERRED_SIZE))
		        				.addComponent(financial_account_jlabel))
		        			.addContainerGap())
		        );
		        gl_Finacial_accnt_jPanel.setVerticalGroup(
		        	gl_Finacial_accnt_jPanel.createParallelGroup(Alignment.TRAILING)
		        		.addGroup(gl_Finacial_accnt_jPanel.createSequentialGroup()
		        			.addComponent(financial_account_jlabel)
		        			.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		        			.addComponent(jLabel12)
		        			.addPreferredGap(ComponentPlacement.RELATED)
		        			.addComponent(financial_accnt_jLabel_img, GroupLayout.PREFERRED_SIZE, 79, GroupLayout.PREFERRED_SIZE)
		        			.addGap(39))
		        );
		        Finacial_accnt_jPanel.setLayout(gl_Finacial_accnt_jPanel);

		        jPanel1.add(Finacial_accnt_jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 140, 120));

		        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		        getContentPane().setLayout(layout);
		        layout.setHorizontalGroup(
		            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		        );
		        layout.setVerticalGroup(
		            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, Short.MAX_VALUE)
		        );

		        pack();
		    }// </editor-fold>//GEN-END:initComponents

		    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
		        // TODO add your handling code here:
		        System.exit(0);
		    }//GEN-LAST:event_exitMousePressed

		    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
		        // TODO add your handling code here:
		        setColor(home_jPanel);
		    }//GEN-LAST:event_jPanel4MouseEntered

		    private void jPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseExited
		        // TODO add your handling code here:
		        resetColor(home_jPanel);
		    }//GEN-LAST:event_jPanel4MouseExited
		     
		    
		    
		    
		    int xx,xy;
		    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
		        // TODO add your handling code here:
		        xx = evt.getX();
		        xy = evt.getY();
		    }//GEN-LAST:event_jPanel2MousePressed

		    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
		        // TODO add your handling code here:
		        int x = evt.getXOnScreen();
		        int y = evt.getYOnScreen();
		        this.setLocation(x - xx, y - xy);  
		    }//GEN-LAST:event_jPanel2MouseDragged

		    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
		        // TODO add your handling code here:
		        setColor(course_jPanel5);
		    }//GEN-LAST:event_jPanel5MouseEntered

		    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
		        // TODO add your handling code here:
		        resetColor(course_jPanel5);
		    }//GEN-LAST:event_jPanel5MouseExited

		    private void jPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseEntered
		        // TODO add your handling code here
		        setColor(grades_jPanel);
		    }//GEN-LAST:event_jPanel6MouseEntered

		    private void jPanel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseExited
		        // TODO add your handling code here:
		        resetColor(grades_jPanel);
		    }//GEN-LAST:event_jPanel6MouseExited

		    private void jPanel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseEntered
		        // TODO add your handling code here:
		        setColor(settings_jPanel);
		    }//GEN-LAST:event_jPanel7MouseEntered

		    private void jPanel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseExited
		        // TODO add your handling code here:
		        resetColor(settings_jPanel);
		        
		    }//GEN-LAST:event_jPanel7MouseExited

		    private void jPanel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseEntered
		        // TODO add your handling code here:
		        setColor(Finacial_accnt_jPanel);
		    }//GEN-LAST:event_jPanel8MouseEntered

		    private void jPanel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseExited
		        // TODO add your handling code here:
		        resetColor(Finacial_accnt_jPanel);
		    }//GEN-LAST:event_jPanel8MouseExited

		    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
		        // TODO add your handling code here:
		        setColor(notifications_jPanel);
		    }//GEN-LAST:event_jPanel3MouseEntered

		    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
		        // TODO add your handling code here:
		        resetColor(notifications_jPanel);
		    }//GEN-LAST:event_jPanel3MouseExited

		    /*private void jPanel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed
		        // TODO add your handling code here:
		    	JFrame_Student_Profile student_profile=new JFrame_Student_Profile(username);
		    	student_profile.showData(username);
		    	student_profile.setVisible(true);
				setVisible(false);
		        //new user_data().show();
		   }//GEN-LAST:event_jPanel4MousePressed*/
		    
		    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed
		        // TODO add your handling code here:
		    	JFrame_Student_Profile student_profile=new JFrame_Student_Profile(username);
		    	student_profile.showData(username);
		    	student_profile.setVisible(true);
				//setVisible(false);
		        //new user_data().show();
		   }//GEN-LAST:event_jPanel4MousePressed
		    
		    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed
		        // TODO add your handling code here:
		    	JFrame_Student_Home_Settings settings = new JFrame_Student_Home_Settings(username);
				settings.setVisible(true);
		    	//student_profile.showData(username);
		    	//student_profile.setVisible(true);
				//setVisible(false);
		        //new user_data().show();
		   }//GEN-LAST:event_jPanel4MousePressed

		    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
		        // TODO add your handling code here:
		        //just a sample.
		     //   new Students().show();
		    }//GEN-LAST:event_jPanel5MousePressed
		 public void setColor(JPanel panel)
		 {
		     panel.setBackground(new java.awt.Color(197, 197, 197));
		 }
		 
		 public void resetColor(JPanel panel)
		 {
		     panel.setBackground(new java.awt.Color(240,240,240));
		 }

		    // Variables declaration - do not modify//GEN-BEGIN:variables
		    private javax.swing.JLabel exit;
		    private javax.swing.JLabel jLabel1;
		    private javax.swing.JLabel jLabel10;
		    private javax.swing.JLabel financial_accnt_jLabel_img;
		    private javax.swing.JLabel jLabel12;
		    private javax.swing.JLabel jLabel13;
		    private javax.swing.JLabel jLabel14;
		    private javax.swing.JLabel jLabel15;
		    private javax.swing.JLabel jLabel16;
		    private javax.swing.JLabel notifications_jLabel_img;
		    private javax.swing.JLabel profile_jlabel_img;
		    private javax.swing.JLabel jLabel4;
		    private javax.swing.JLabel courses_jLabel_img;
		    private javax.swing.JLabel jLabel6;
		    private javax.swing.JLabel grades_jLabel_img;
		    private javax.swing.JLabel jLabel8;
		    private javax.swing.JLabel settings_jLabel_img;
		    private javax.swing.JPanel jPanel1;
		    private javax.swing.JPanel jPanel2;
		    private javax.swing.JPanel notifications_jPanel;
		    private javax.swing.JPanel home_jPanel;
		    private javax.swing.JPanel course_jPanel5;
		    private javax.swing.JPanel grades_jPanel;
		    private javax.swing.JPanel settings_jPanel;
		    private javax.swing.JPanel Finacial_accnt_jPanel;
		    private javax.swing.JSeparator jSeparator1;
		    private javax.swing.JTextField jTextField1;
		    private JLabel settings_jlabel;
		    private JLabel courses_jlabel;
		    private JLabel financial_account_jlabel;
		    private JLabel grades_jlabel;
		    private JLabel notifications_jlabel;
}
